<a href="https://colab.research.google.com/github/aminul01-g/pytorch/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.6.0+cu124


In [ ]:
if torch.cuda.is_available():
  print("Gpu is available!")
  print(f"Using Gpu:{torch.cuda.get_device_name(0)}")
else:
  print("Gpu not available. using CPU.")

Gpu is available!
Using Gpu:Tesla T4


##Creating Tensor##

In [ ]:
# Using Empty

a = torch.empty(2,3)

In [ ]:
# Check Type

type(a)

torch.Tensor

In [ ]:
# Using zeros

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Using Ones

torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# Using rand

torch.rand(2,3)

tensor([[0.6113, 0.3210, 0.8512],
        [0.9607, 0.1839, 0.0082]])

In [ ]:
# Use of Seed

torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
# Usint tensor

torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Arange

print("Using arange ->",torch.arange(0,10,2))

Using arange -> tensor([0, 2, 4, 6, 8])


In [ ]:
# Using linspace

print("Using linspace ->",torch.linspace(0,10,5))

Using linspace -> tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [ ]:
# Using eye

print("Using eye ->",torch.eye(3))

Using eye -> tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
# Using Full

print("Using Full ->",torch.full((3,3),5))

Using Full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[138168959491456,       242225024,        10780024],
        [       10779960,        10781792, 138168953226784]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

###Tensor Data Type##

In [ ]:
# Find Data Type

x.dtype

torch.int64

In [ ]:
#Assign Data Type

torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
# Using to()

x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical Operation##

## 1. Scalar Operation##

In [ ]:
x = torch.rand(2,2)
x

tensor([[0.1053, 0.2695],
        [0.3588, 0.1994]])

In [ ]:
# Additiion

x + 4

tensor([[4.1053, 4.2695],
        [4.3588, 4.1994]])

In [ ]:
# Subtraction

x - 2

tensor([[-1.8947, -1.7305],
        [-1.6412, -1.8006]])

In [ ]:
# Multiplication

x * 3

tensor([[0.3159, 0.8085],
        [1.0764, 0.5981]])

In [ ]:
# Division
x / 2

tensor([[0.0527, 0.1347],
        [0.1794, 0.0997]])

In [ ]:
# int Division
(x * 100) // 2

tensor([[ 5., 13.],
        [17.,  9.]])

In [ ]:
# Mod

((x*100)//2)%2

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
# Power

x**2

tensor([[0.0111, 0.0726],
        [0.1287, 0.0397]])

### 2. Element wise Operation ##

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.6343, 0.3644, 0.7104],
        [0.9464, 0.7890, 0.2814]])
tensor([[0.7886, 0.5895, 0.7539],
        [0.1952, 0.0050, 0.3068]])


In [ ]:
# Add

a + b

tensor([[1.4230, 0.9539, 1.4643],
        [1.1417, 0.7941, 0.5882]])

In [ ]:
# Sub

a - b

tensor([[-0.1543, -0.2251, -0.0435],
        [ 0.7512,  0.7840, -0.0254]])

In [ ]:
# Multiplication

a * b

tensor([[0.5003, 0.2148, 0.5356],
        [0.1848, 0.0040, 0.0863]])

In [ ]:
# Division

a/b

tensor([[  0.8044,   0.6182,   0.9423],
        [  4.8472, 156.3745,   0.9172]])

In [ ]:
# Mod

a % b

tensor([[0.6343, 0.3644, 0.7104],
        [0.1654, 0.0019, 0.2814]])

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
# abs

torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# Negative

torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
d = torch.tensor([1.2, 3.6, 4.4,])

In [ ]:
# Round
torch.round(d)

tensor([1., 4., 4.])

In [ ]:
# Ceil

torch.ceil(d)

tensor([2., 4., 5.])

In [ ]:
# Floor

torch.floor(d)

tensor([1., 3., 4.])

In [ ]:
# clamp

torch.clamp(d,min=2,max=3)

tensor([2., 3., 3.])

### 3. Reduction Operation ###

In [ ]:
e = torch.randint(size=(2,3),low=0,high=10, dtype=torch.float32)
e

tensor([[8., 8., 6.],
        [0., 0., 0.]])

In [ ]:
# Sum

torch.sum(e)

tensor(33)

In [ ]:
# sum along columns

torch.sum(e, dim=0)

tensor([ 9, 14, 10])

In [ ]:
# sum along rows

torch.sum(e, dim=1)

tensor([15, 18])

In [ ]:
# mean

torch.mean(e)

tensor(3.6667)

In [ ]:
# mean col
torch.mean(e, dim=0)

tensor([4., 4., 3.])

In [ ]:
# median

torch.median(e)

tensor(0.)

In [ ]:
# max and min

torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
# product

torch.prod(e)

tensor(0.)

In [ ]:
# Standard Deviation

torch.std(e)

tensor(4.0825)

In [ ]:
# Variance

torch.var(e)

tensor(16.6667)

In [ ]:
# argmax

torch.argmax(e)

tensor(0)

In [ ]:
# argmin

torch.argmin(e)

tensor(3)

### 4. Matrix Operation

In [ ]:
f = torch.randint(size=(2,3),low=0,high=10,)
g = torch.randint(size=(3,2),low=0,high=10,)

print(f)
print(g)

tensor([[5, 3, 7],
        [7, 5, 9]])
tensor([[1, 5],
        [1, 9],
        [1, 4]])


In [ ]:
# matrix multiplication

In [ ]:
torch.matmul(f,g)

tensor([[ 15,  80],
        [ 21, 116]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

# dot product
torch.dot(vector1,vector2)

tensor(11)

In [ ]:
# transpose

torch.transpose(f, 0,1)

tensor([[5, 7],
        [3, 5],
        [7, 9]])

In [ ]:
h = torch.randint(size=(3,3), low = 0, high = 10, dtype=torch.float32)
h

tensor([[0., 3., 7.],
        [5., 7., 1.],
        [5., 7., 5.]])

In [ ]:
# determinant
torch.det(h)

tensor(-60.0000)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-4.6667e-01, -5.6667e-01,  7.6667e-01],
        [ 3.3333e-01,  5.8333e-01, -5.8333e-01],
        [-1.4901e-08, -2.5000e-01,  2.5000e-01]])

### 5. Comparison Operations

In [ ]:
i = torch.randint(size=(2,3), low = 0, high = 10, dtype=torch.int32)
j = torch.randint(size=(2,3), low = 0, high = 10, dtype=torch.int32)
print(i)
print(j)

tensor([[6, 7, 6],
        [0, 9, 5]], dtype=torch.int32)
tensor([[2, 9, 1],
        [7, 8, 6]], dtype=torch.int32)


In [ ]:
# greater than

i > j

tensor([[ True, False,  True],
        [False,  True, False]])

In [ ]:
# less than

i < j

tensor([[False,  True, False],
        [ True, False,  True]])

In [ ]:
# equal to

i == j

tensor([[True, True, True],
        [True, True, True]])

In [ ]:
# not equal to

i !=j

tensor([[False, False, False],
        [False, False, False]])

### 6.Special Function

In [ ]:
k = torch.randint(size=(2,3), low = 0, high = 10, dtype=torch.float32)
k

tensor([[6., 9., 0.],
        [5., 9., 5.]])

In [ ]:
# log

torch.log(k)

tensor([[1.7918, 2.1972,   -inf],
        [1.6094, 2.1972, 1.6094]])

In [ ]:
# exp

torch.exp(k)

tensor([[4.0343e+02, 8.1031e+03, 1.0000e+00],
        [1.4841e+02, 8.1031e+03, 1.4841e+02]])

In [ ]:
#sqrt

torch.sqrt(k)

tensor([[2.4495, 3.0000, 0.0000],
        [2.2361, 3.0000, 2.2361]])

In [ ]:
# sigmoid

torch.sigmoid(k)

tensor([[0.9975, 0.9999, 0.5000],
        [0.9933, 0.9999, 0.9933]])

In [ ]:
# softmax

torch.softmax(k, dim=0)

tensor([[0.7311, 0.5000, 0.0067],
        [0.2689, 0.5000, 0.9933]])

In [ ]:
# relu

torch.relu(k)

tensor([[6., 9., 0.],
        [5., 9., 5.]])

### 7. Inplace Operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.6044, 0.7581, 0.9037],
        [0.9555, 0.1035, 0.6258]])
tensor([[0.2849, 0.4452, 0.1258],
        [0.9554, 0.1330, 0.7672]])


In [ ]:
m + n

tensor([[0.8894, 1.2033, 1.0294],
        [1.9109, 0.2366, 1.3931]])

In [ ]:
m.add_(n)

tensor([[0.8894, 1.2033, 1.0294],
        [1.9109, 0.2366, 1.3931]])

In [ ]:
m

tensor([[0.8894, 1.2033, 1.0294],
        [1.9109, 0.2366, 1.3931]])

### 8. Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.6757, 0.6625, 0.2297],
        [0.9545, 0.6099, 0.5643]])

In [ ]:
b = a
b

tensor([[0.6757, 0.6625, 0.2297],
        [0.9545, 0.6099, 0.5643]])

In [ ]:
a[0][0] = 0
a

tensor([[0.0000, 0.6625, 0.2297],
        [0.9545, 0.6099, 0.5643]])

In [ ]:
b

tensor([[0.0000, 0.6625, 0.2297],
        [0.9545, 0.6099, 0.5643]])

In [ ]:
id(a)

138163872364880

In [ ]:
id(b)

138163872364880

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.6625, 0.2297],
        [0.9545, 0.6099, 0.5643]])

In [ ]:
b

tensor([[0.0000, 0.6625, 0.2297],
        [0.9545, 0.6099, 0.5643]])

In [ ]:
a[0][0] = 10
a

tensor([[10.0000,  0.6625,  0.2297],
        [ 0.9545,  0.6099,  0.5643]])

In [ ]:
b

tensor([[0.0000, 0.6625, 0.2297],
        [0.9545, 0.6099, 0.5643]])

In [ ]:
id(a)

138163872364880

In [ ]:
id(b)

138163886593456

## Tensor Operation on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
gpu  = torch.device('cuda')

In [ ]:
# Creating a new tensor on GPU

torch.rand((2,3), device= gpu)

tensor([[0.9877, 0.1289, 0.5621],
        [0.5221, 0.7445, 0.5955]], device='cuda:0')

In [ ]:
# Moving an existing tensor on GPU
a = torch.rand(2,3)
a

tensor([[0.2234, 0.2469, 0.4761],
        [0.7792, 0.3722, 0.2147]])

In [ ]:
b = a.to(gpu)
b

tensor([[0.2234, 0.2469, 0.4761],
        [0.7792, 0.3722, 0.2147]], device='cuda:0')

In [ ]:
b + 5

tensor([[5.2234, 5.2469, 5.4761],
        [5.7792, 5.3722, 5.2147]], device='cuda:0')

## Reshaping Tensors

In [ ]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape

a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flatten

a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.3288, 0.1265, 0.6783, 0.8870],
         [0.0293, 0.6161, 0.7583, 0.5907],
         [0.3219, 0.7610, 0.7628, 0.6870]],

        [[0.4121, 0.3676, 0.5535, 0.4117],
         [0.3510, 0.8196, 0.9297, 0.4505],
         [0.3881, 0.5073, 0.4701, 0.6202]]])

In [ ]:
# permute

b.permute(2,0,1)

tensor([[[0.3288, 0.0293, 0.3219],
         [0.4121, 0.3510, 0.3881]],

        [[0.1265, 0.6161, 0.7610],
         [0.3676, 0.8196, 0.5073]],

        [[0.6783, 0.7583, 0.7628],
         [0.5535, 0.9297, 0.4701]],

        [[0.8870, 0.5907, 0.6870],
         [0.4117, 0.4505, 0.6202]]])

In [ ]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
# unsqueeze
#image size
c = torch.rand(2,2,3)
c

tensor([[[0.9771, 0.8957, 0.5197],
         [0.4079, 0.8579, 0.9665]],

        [[0.2009, 0.2629, 0.8852],
         [0.5680, 0.3550, 0.4010]]])

In [ ]:
c.unsqueeze(0)

tensor([[[[0.9771, 0.8957, 0.5197],
          [0.4079, 0.8579, 0.9665]],

         [[0.2009, 0.2629, 0.8852],
          [0.5680, 0.3550, 0.4010]]]])

In [ ]:
c.unsqueeze(0).shape

torch.Size([1, 2, 2, 3])

In [ ]:
# squeeze

d = torch.rand(1,20)
d



tensor([[0.2125, 0.9111, 0.8295, 0.8909, 0.7374, 0.1738, 0.4939, 0.2489, 0.8199,
         0.1290, 0.8957, 0.7768, 0.3288, 0.8266, 0.5552, 0.2835, 0.2279, 0.8117,
         0.9010, 0.1004]])

In [ ]:
d.squeeze(0)

tensor([0.2125, 0.9111, 0.8295, 0.8909, 0.7374, 0.1738, 0.4939, 0.2489, 0.8199,
        0.1290, 0.8957, 0.7768, 0.3288, 0.8266, 0.5552, 0.2835, 0.2279, 0.8117,
        0.9010, 0.1004])

In [ ]:
d.squeeze(0).shape

torch.Size([20])

## Numpy and PyTorch

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b = a.numpy()

In [ ]:
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,3])
c


array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])