<a href="https://colab.research.google.com/github/aminul01-g/pytorch/blob/main/Dataset%26DataLoader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import make_classification
import torch

In [2]:
# Step_1: Create a synthetic classficatoin dataset using sklearn
x, y = make_classification(
    n_samples = 10, # Number of samples
    n_features= 2,  # Number of features
    n_informative=2, #NUmber of informative features
    n_redundant= 0, # Number of redundant features
    n_classes= 2,  # Number of classes
    random_state= 42 # For reproducibility
)

x

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [3]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [4]:
# Convert the data to PyTorch tensors
x = torch.tensor(x, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

x

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [5]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [14]:
from torch.utils.data import Dataset, DataLoader

# Dataset

(Fatch the data for the dataloader)


In [7]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return self.features.shape[0]

  def __getitem__(self, index):

    return self.features[index], self.labels[index]

In [8]:
dataset = CustomDataset(x, y)

In [9]:
len(dataset)

10

In [10]:
dataset[0]

(tensor([ 1.0683, -0.9701]), tensor(1))

# DataLoader
(Where we create batchs of data)

In [15]:
dataloader = DataLoader(dataset, batch_size = 2 , shuffle = True)

In [17]:
for batch_features, batch_labels in dataloader:

  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 1.0683, -0.9701],
        [ 1.7273, -1.1858]])
tensor([1, 1])
--------------------------------------------------
tensor([[-0.7206, -0.9606],
        [-2.8954,  1.9769]])
tensor([0, 0])
--------------------------------------------------
tensor([[-0.5872, -1.9717],
        [ 1.8997,  0.8344]])
tensor([0, 1])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-1.1402, -0.8388]])
tensor([0, 0])
--------------------------------------------------
tensor([[-0.9382, -0.5430],
        [ 1.7774,  1.5116]])
tensor([1, 1])
--------------------------------------------------


___________________<h1> Now Train a NN using Dataset & DataLoader </h2>________________

In [18]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [20]:
df  = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [21]:
df.shape

(569, 33)

In [22]:
df.drop (columns=["id", "Unnamed: 32"], inplace=True)

df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

# Train Test Split

In [23]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size = 0.2)

# Scaling

In [24]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.fit_transform(x_test)

In [25]:
x_train

array([[-0.66842342, -0.48000926, -0.67988443, ..., -0.38814486,
        -1.11986102, -1.31557579],
       [-0.69207794, -0.4730962 , -0.71960096, ..., -1.09763086,
         0.49323779, -1.01189968],
       [ 0.55274113,  0.87494993,  0.45182337, ..., -0.23080411,
         0.07844095,  0.0372649 ],
       ...,
       [-0.70981883, -0.43392221, -0.69312327, ..., -0.2116908 ,
        -0.69518807, -0.35141814],
       [ 0.79519995,  0.00390474,  0.69524731, ..., -0.46612716,
        -0.61453312, -1.34969041],
       [-0.47623046, -0.7196619 , -0.46421936, ..., -0.46994982,
         0.41916693, -0.47389524]])

In [26]:
y_train

275    B
188    B
10     M
269    B
95     M
      ..
219    M
67     B
530    B
157    B
502    B
Name: diagnosis, Length: 455, dtype: object

In [27]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

y_train

array([0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,

# Numpy to Tensor

In [56]:
x_train_tensor = torch.from_numpy(x_train.astype(np.float32))
x_test_tensor =  torch.from_numpy(x_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

x_train_tensor.shape

torch.Size([455, 30])

In [57]:
y_train_tensor.shape

torch.Size([455])

In [58]:
from torch.utils.data import Dataset, DataLoader

# Dataset

In [33]:
class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return len(self.features)

  def __getitem__(self, index):
    return self.features[index], self.labels[index]

In [34]:
train_dataset = CustomDataset(x_train_tensor, y_train_tensor)
test_dataset = CustomDataset(x_test_tensor, y_test_tensor)

In [35]:
train_dataset[10]

(tensor([-0.4230, -0.4086, -0.4757, -0.4558, -1.2275, -1.0983, -0.9366, -0.7822,
         -1.2771, -1.0969, -0.3752, -0.5958, -0.3589, -0.3790,  0.1486, -0.7569,
         -0.9707, -1.0238, -0.0941, -1.0783, -0.5217, -0.7944, -0.5636, -0.5254,
         -1.1284, -0.9956, -1.1305, -1.2037, -1.2104, -1.3200]),
 tensor(0.))

# DataLoad

In [44]:
train_loader = DataLoader(train_dataset, batch_size= 32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size= 32, shuffle = True)

# Defining the Model

In [54]:
import torch.nn as nn

class simpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

# Importent Peramenters

In [62]:
learning_rate = 0.1
epochs = 25

# Creat Model

In [61]:
model = simpleNN(x_train_tensor.shape[1])

# Define Optimizer

Optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

# Define Loss Function

loss_fun = nn.BCELoss()

# Train Pipline

In [64]:
# Define Loop

for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # Forward Pass
    y_pred = model(batch_features)

    # Loss Calculate
    loss = loss_fun(y_pred, batch_labels.view(-1,1))

    # Clear gradients
    Optimizer.zero_grad()

    # Backward Pass

    loss.backward()

    # Perameters Update

    Optimizer.step()

    # Print LOss in each Epoch

  print(f"Epoch: {epoch+1}, Loss: {loss.item():.4f}")

Epoch: 1, Loss: 0.1809
Epoch: 2, Loss: 0.1825
Epoch: 3, Loss: 0.0691
Epoch: 4, Loss: 0.0928
Epoch: 5, Loss: 0.0341
Epoch: 6, Loss: 0.0645
Epoch: 7, Loss: 0.2821
Epoch: 8, Loss: 0.0754
Epoch: 9, Loss: 0.0904
Epoch: 10, Loss: 0.0832
Epoch: 11, Loss: 0.0917
Epoch: 12, Loss: 0.0612
Epoch: 13, Loss: 0.0112
Epoch: 14, Loss: 0.0872
Epoch: 15, Loss: 0.1840
Epoch: 16, Loss: 0.0608
Epoch: 17, Loss: 0.3702
Epoch: 18, Loss: 0.0361
Epoch: 19, Loss: 0.0209
Epoch: 20, Loss: 0.0051
Epoch: 21, Loss: 0.0056
Epoch: 22, Loss: 0.0284
Epoch: 23, Loss: 0.0438
Epoch: 24, Loss: 0.0024
Epoch: 25, Loss: 0.0662


# Evaluation

In [65]:
# Model evaluation using test_loader
model.eval() # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    # Forward Pass
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.8).float() # Convert probabilities to binary predictions

    # Calculate accuracy for the current batch
    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

# Calculate the average accuracy across all batches
average_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f"Test Accuracy: {average_accuracy * 100:.2f}%")

Test Accuracy: 95.66%
