<a href="https://colab.research.google.com/github/aminul01-g/pytorch/blob/main/NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import torch.nn as nn

 # Single layer NN Model

In [8]:
# Create Model Class

class Model(nn.Module):
    def __init__(self, num_fetures):
        super().__init__()
        self.linear = nn.Linear(num_fetures, 1)
        self.sigmoid = nn.Sigmoid()

    def forward (self, fetures):
      out = self.linear(fetures) # z = wx+b
      out = self.sigmoid(out)
      return out # return output

In [9]:
# Create dataset

features = torch.rand(10, 5) # 5 Inputs which have 10 rows

# Create Model

model = Model(features.shape[1])

# Call model for forward pass

   # mdoel.forward(features)

model(features)

tensor([[0.5240],
        [0.6001],
        [0.5888],
        [0.5566],
        [0.5778],
        [0.6026],
        [0.5953],
        [0.6280],
        [0.6118],
        [0.6122]], grad_fn=<SigmoidBackward0>)

In [10]:
model.linear.weight

Parameter containing:
tensor([[ 0.0940, -0.0826,  0.2274,  0.1962, -0.3113]], requires_grad=True)

In [11]:
model.linear.bias

Parameter containing:
tensor([0.3538], requires_grad=True)

In [12]:
!pip install torchinfo

In [14]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Create a NN with hidden layer

In [31]:
# Create Model Class

"""class Model(nn.Module):
    def __init__(self, num_fetures):
        super().__init__()
        self.linear1 = nn.Linear(num_fetures, 3)
        self.relu = nn.ReLU()

        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward (self, fetures):
      out = self.linear1(fetures) # z = wx+b
      out = self.relu(out)

      out = self.linear2(out)
      out = self.sigmoid(out)
      return out"""

  # Sequential Container

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()

    self.layers = nn.Sequential(
          nn.Linear(num_features, 3),
          nn.ReLU(),
          nn.Linear(3, 1),
          nn.Sigmoid()
    )


  def forward(self, features):
      return self.layers(features)

In [32]:
# Create dataset

features = torch.rand(10, 5) # 5 Inputs which have 10 rows

# Create Model

model = Model(features.shape[1])

# Call model for forward pass

   # mdoel.forward(features)

model(features)

tensor([[0.3719],
        [0.3666],
        [0.3744],
        [0.3553],
        [0.3523],
        [0.3703],
        [0.3780],
        [0.3443],
        [0.3805],
        [0.3779]], grad_fn=<SigmoidBackward0>)

In [35]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00